name: Release Obsidian plugin

on:
  push:
    tags:
      - '*'

env:
  PLUGIN_NAME: 'EncryptAll'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        id: build
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build completed"
          
          echo "Creating release directory..."
          mkdir -p ${{ env.PLUGIN_NAME }}
          echo "Copying files..."
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}/
          echo "Creating zip file..."
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Version: $VERSION"
          zip -r ${{ env.PLUGIN_NAME }}-$VERSION.zip ${{ env.PLUGIN_NAME }}
          echo "Listing files..."
          ls -la
          echo "Listing plugin directory..."
          ls -la ${{ env.PLUGIN_NAME }}

      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            main.js
            manifest.json
            styles.css
            ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip
          body: |
            ## Release Notes
            
            ### Changes in this release:
            - 优化了文件加密和解密功能
            - 改进了用户界面样式
            - 修复了文件删除相关的问题
            - 提升了整体性能和稳定性